### ISSUE TITLE
Gradient background for process bar

### ISSUE THREAD

**Issue by radulescupetru** [biigpongsatorn/vue-slide-bar#32]
Any idea on how I could achieve a gradient background for the process bar?

**Comment by biigpongsatorn** [comment]
Write this css as global
```css
.vue-slide-bar-process {
    position: absolute;
    border-radius: 15px;
    transition: all 0s;
    z-index: 1;
    width: 0;
    height: 100%;
    top: 0;
    left: 0;
    will-change: width;
    background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(9,9,121,1) 35%, rgba(0,212,255,1) 100%) !important;
}
```

## Result:

![image](https://user-images.githubusercontent.com/10693658/70433149-87eac680-1ab3-11ea-80ac-0a5efc78d87e.png)
